football_manager/football_manager/urls.py
from django.conf.urls import url
from django.contrib import admin
from app_football.views import (
    ActionsView,
    CreateTeamView,
    CookiesView,
    EditPlayerView,
    GameView,
    IndexView,
    LeagueEndView,
    LoginUserView,
    LogoutUserView,
    LowEnergyView,
    MainView,
    MatchView,
    PersonalTrainingView,
    PlayerView,
    RegisterUserView,
    RoundView,
    ScheduleView,
    TableView,
    TeamView,
    TeamTrainingView,
    TrainingView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^index$', IndexView.as_view(), name='index'),
    url(r'^low_energy$', LowEnergyView.as_view(), name='low-energy'),
    url(r'^register$', RegisterUserView.as_view(), name='register'),
    url(r'^login$', LoginUserView.as_view(), name='login'),
    url(r'^logout$', LogoutUserView.as_view(), name='logout'),
    url(r'^create_team$', CreateTeamView.as_view(), name='create-team'),
    url(r'^actions$', ActionsView.as_view(), name='actions'),
    url(r'^team$', TeamView.as_view(), name='team'),
    url(r'^edit_player/(?P<pk>(\d)+)$', EditPlayerView.as_view(), name='edit-player'),
    url(r'^training$', TrainingView.as_view(), name='training'),
    url(r'^personal_training/(?P<player_pk>(\d)+)$', PersonalTrainingView.as_view(), name='personal-training'),
    url(r'^team_training$', TeamTrainingView.as_view(), name='team-training'),
    url(r'^table$', TableView.as_view(), name='table'),
    url(r'^schedule$', ScheduleView.as_view(), name='schedule'),
    url(r'^round/(?P<round_no>(\d)+)$', RoundView.as_view(), name='round'),
    url(r'^match$', MatchView.as_view(), name='match'),
    url(r'^game$', GameView.as_view(), name='game'),
    url(r'^league_end$', LeagueEndView.as_view(), name='league-end'),
    url(r'^cookies$', CookiesView.as_view(), name='cookies'),


]

football_manager/app_football/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import AbstractUser

POSITION_CHOICE = {
    1: 'GK',
    2: 'DF',
    3: 'MF',
    4: 'ST'
}


class User(AbstractUser):
    energy = models.IntegerField(validators=[MaxValueValidator(10), MinValueValidator(0)], default=10)


class Team(models.Model):
    name = models.CharField(max_length=64)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, default='null', blank=True)
    player_id = models.IntegerField()
    is_user_team = models.BooleanField(default=False)
    played = models.IntegerField(default=0, null=True)
    wins = models.IntegerField(default=0, null=True)
    draws = models.IntegerField(default=0, null=True)
    loses = models.IntegerField(default=0, null=True)
    goals_sum = models.IntegerField(default=0, null=True)
    points = models.IntegerField(default=0)

    def __str__(self):
        return '{}'.format(self.name)


class Player(models.Model):
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    position = models.IntegerField(choices=POSITION_CHOICE.items())
    attack = models.IntegerField()
    defence = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.full_name)

    @property
    def full_name(self):
        return "{} {}".format(self.name, self.surname)


class Match(models.Model):
    player_id = models.IntegerField(default=None)
    home_team = models.ForeignKey(Team, related_name='home', on_delete=models.CASCADE)
    away_team = models.ForeignKey(Team, related_name='away', null=True, default=None, on_delete=models.CASCADE)
    round_no = models.IntegerField()
    home_team_goals = models.IntegerField(null=True, default=None)
    away_team_goals = models.IntegerField(null=True, default=None)

football_manager/app_football/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate

from .models import User, Player



class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.PasswordInput()
        self.fields['password'].widget.attrs['class'] = 'password-field'
        self.fields['username'].help_text = ""
        self.fields['username'].widget.attrs['class'] = 'login-field'
        self.fields['email'].widget.attrs['class'] = 'email-field'


    def clean(self):
        cleaned_data = super().clean()
        raw_password = cleaned_data['password']
        cleaned_data['password'] = make_password(raw_password)
        return cleaned_data


class AuthForm(forms.Form):
    login = forms.CharField(widget=forms.TextInput(attrs={'class': 'login-field'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'password-field'}))

    def clean(self):
        """
        Metoda dorzuca do cleaned_data obiekt użytkowinika pod kluczem 'user'.
        """
        cleaned_data = super().clean()

        login = cleaned_data['login']
        password = cleaned_data['password']
        user = authenticate(username=login, password=password)

        if user is None:
            raise forms.ValidationError('Wrong username or password')

        cleaned_data['user'] = user
        return cleaned_data


class CreateTeamForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'teamname-field'}))


class EditPlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ['name', 'surname']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'name-field'
        self.fields['surname'].widget.attrs['class'] = 'surname-field'

football_manager/app_football/views.py
from .management.commands._private import (
    create_teams,
    create_players,
    create_players_again,
    create_rounds,
    match_result,
    next_round,
)

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from random import choice, randint

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from .models import Player, Team, Match
from django.views import View
from .forms import (
    AuthForm,
    CreateTeamForm,
    EditPlayerForm,
    RegisterUserForm
)
from django.contrib.auth import get_user_model, authenticate, login, logout


class IndexView(View):

    def get(self, request):
        return render(request, 'app_football/index.html', {})


class MainView(View):

    def get(self, request):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('actions'))
        else:
            return render(request, 'app_football/main.html', {})


class LowEnergyView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'app_football/low_energy.html', {})


class RegisterUserView(View):
    def get(self, request):
        form = RegisterUserForm()
        ctx = {'form': form}
        return render(request, 'app_football/register_user_form.html', ctx)

    def post(self, request):
        form = RegisterUserForm(data=request.POST)
        ctx = {'form': form}
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse('create-team'))
        else:
            return render(request, 'app_football/register_user_form.html', ctx)


class CookiesView(View):

    def get(self, request):
        return render(request, 'app_football/cookies.html', {})


class LoginUserView(View):

    def get(self, request):
        form = AuthForm()
        ctx = {'form': form}
        return render(request, 'app_football/login.html', ctx)

    def post(self, request):
        form = AuthForm(data=request.POST)
        ctx = {'form': form}
        if form.is_valid():
            user = form.cleaned_data['user']
            login(request, user)
            return render(request, 'app_football/actions_view.html', {})
        else:
            return render(request, 'app_football/login.html', ctx)


class LogoutUserView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('main'))


class CreateTeamView(LoginRequiredMixin, View):

    def get(self, request):
        form = CreateTeamForm()
        ctx = {'form': form}
        return render(request, 'app_football/create_team.html', ctx)

    def post(self, request):
        form = CreateTeamForm(data=request.POST)
        ctx = {'form': form}
        if form.is_valid():
            user = self.request.user
            user_id = user.id
            team_name = form.cleaned_data['name']
            Team.objects.create(name=team_name, user=user, player_id=user_id, is_user_team=True)

            create_teams(user_id)
            create_players(user)
            create_rounds(user_id)
            return HttpResponseRedirect(reverse('actions'))
        else:
            return render(request, 'app_football/create_team.html', ctx)


class TeamView(LoginRequiredMixin, View):

    def get(self, request):
        team = Team.objects.get(user=self.request.user)
        players = Player.objects.filter(team=team)
        ctx = {'players': players}
        return render(request, 'app_football/team_view.html', ctx)


class PlayerView(LoginRequiredMixin, View):

    def get(self, request, pk):
        player = Player.objects.get(pk=pk)
        ctx = {'player': player}
        return render(request, 'app_football/player_view.html', ctx)


class EditPlayerView(LoginRequiredMixin, View):

    def get(self, request, pk):
        player = Player.objects.get(pk=pk)
        form = EditPlayerForm(instance=player)
        ctx = {'player': player,
               'form': form}
        return render(request, 'app_football/player_edit.html', ctx)

    def post(self, request, pk):
        player = Player.objects.get(pk=pk)
        form = EditPlayerForm(instance=player, data=request.POST)
        ctx = {'player': player,
               'form': form}
        if form.is_valid():
            player.name = form.cleaned_data['name']
            player.surname = form.cleaned_data['surname']
            player.save()
            return redirect(reverse('team'))
        return render(request, 'app_football/player_edit.html', ctx)


class ActionsView(LoginRequiredMixin, View):

    def get(self, request):
        ctx = {}
        return render(request, 'app_football/actions_view.html', ctx)


class TableView(LoginRequiredMixin, View):

    def get(self, request):
        user = self.request.user
        teams = Team.objects.filter(player_id=user.id).order_by('-points', '-goals_sum')

        ctx = {'teams': teams}
        return render(request, 'app_football/table_view.html', ctx)


class TrainingView(LoginRequiredMixin, View):

    def get(self, request):
        team = Team.objects.get(user=self.request.user)
        players = Player.objects.filter(team=team)
        ctx = {'players': players}
        return render(request, 'app_football/training_view.html', ctx)


class PersonalTrainingView(LoginRequiredMixin, View):

    def get(self, request, player_pk):
        player = Player.objects.get(pk=player_pk)
        ctx = {'player': player}
        return render(request, 'app_football/personal_training.html', ctx)

    def post(self, request, player_pk):
        player = Player.objects.get(pk=player_pk)
        team = player.team
        user = self.request.user
        ctx = {'player': player}
        if request.POST.get("train_att"):
            if user.energy < 2:
                return redirect(reverse('low-energy'))
            else:
                if player.attack == 99:
                    player.attack += 1
                else:
                    player.attack += 2
                player.save()
                user.energy -= 2
                user.save()
                return redirect(reverse('personal-training', kwargs={'player_pk': player_pk}))
        elif request.POST.get("train_def"):
            if user.energy < 2:
                return redirect(reverse('low-energy'))
            else:
                if player.defence == 99:
                    player.defence += 1
                else:
                    player.defence += 2
                player.save()
                user.energy -= 2
                user.save()
                return render(request, 'app_football/personal_training.html', ctx)
        return render(request, 'app_football/personal_training.html', ctx)


class TeamTrainingView(LoginRequiredMixin, View):

    def get(self, request):
        team = Team.objects.get(user=self.request.user)
        players = team.player_set.all()
        ctx = {'players': players}
        return render(request, 'app_football/team_training.html', ctx)

    def post(self, request):
        team = Team.objects.get(user=self.request.user)
        players = team.player_set.all()
        user = self.request.user
        ctx = {'players': players}
        if request.POST.get("team_train"):
            if user.energy < 4:
                return redirect(reverse('low-energy'))
            else:
                user.energy -= 4
                user.save()

                i = 0
                p = []
                player_it = []
                while i < 3:
                    player = choice(players)
                    if len(p) == len(players):
                        break
                    if player in p:
                        continue
                    elif player.attack == 100 and player.defence == 100:
                        p.append(player)
                    elif player.attack == 100 and player.defence == 99:
                        player.defence += 1
                        player_it.append(str(player) + ' defence')
                        player.save()
                        i += 1
                    elif player.attack == 100 and player.defence < 99:
                        player.defence += 2
                        player_it.append(str(player) + ' defence')
                        player.save()
                        i += 1
                    elif player.attack == 99 and player.defence == 100:
                        player.attack += 1
                        player_it.append(str(player) + ' attack')
                        player.save()
                        i += 1
                    elif player.attack < 99 and player.defence == 100:
                        player.attack += 2
                        player_it.append(str(player) + ' attack')
                        player.save()
                        i += 1
                    elif player.attack == 99 and player.defence == 99:
                        atr = randint(0, 1)
                        if atr == 0:
                            player.attack += 1
                            player_it.append(str(player) + ' attack')
                            player.save()
                            i += 1
                        elif atr == 1:
                            player.defence += 1
                            player_it.append(str(player) + ' defence')
                            player.save()
                            i += 1
                    elif player.attack < 99 and player.defence == 99:
                        atr = randint(0, 1)
                        if atr == 0:
                            player.attack += 2
                            player_it.append(str(player) + ' attack')
                            player.save()
                            i += 1
                        elif atr == 1:
                            player.defence += 1
                            player_it.append(str(player) + ' defence')

football_manager/app_football/templates/app_football/cookies.html
{% extends 'app_football/index.html' %}


{% block content %}
<div class="container">
<h2 class="sub-header">Cookies</h2>

<p>To make this site work properly, we sometimes place small data files called cookies on your device.</p>
<p>Most big websites do this too.</p>
<div class="row" style="margin-left: 0;">


    <div class="column-left-two" style="width: 100%; max-width: 100%; padding-right: 20px; border-right: 1px solid white;">

            <h3>What are cookies?</h3>

            <p>A cookie is a small text file that a website saves on your computer or mobile device when you visit the site.
                It enables the website to remember your actions and preferences (such as login, language,
                font size and other display preferences) over a period of time, so you don’t have to keep re-entering
                them whenever you come back to the site or browse from one page to another.</p>

            <h3>How to control cookies</h3>

            <p>You can control and/or delete cookies as you wish – for details, see <a href="aboutcookies.org">aboutcookies.org</a>.
                You can delete all cookies that are already on your computer and you can set most browsers to prevent them
                from being placed. If you do this, however, you may have to manually adjust some preferences every time you
                visit a site and some services and functionalities may not work.</p>
        </div>

    <div class="column-right-two" style="width: 100%; max-width: 100%; padding-top: 3px">


            <h3>How do we use cookies?</h3>

            <p>A our page use cookies to remember:</p>

            <p>- your display preferences, such as contrast colour settings or font size</p>
            <p>- if you have agreed (or not) to our use of cookies on this site</p>
            <p>- if you are already registered user</p>



            <p>Enabling these cookies is not strictly necessary for the website to work but it will provide you with a better
                browsing experience. You can delete or block these cookies, but if you do that some features
                of this site may not work as intended.</p>

            <p>The cookie-related information is not used to identify you personally and the pattern data is fully under our control.
                These cookies are not used for any purpose other than those described here.</p>
        </div>

    </div>
</div>
{% endblock %}

football_manager/app_football/templates/app_football/create_team.html
{% extends 'app_football/index.html' %}

{% block content %}

{% load static %}

<div class="container login">

	<h2>Team Creator</h2>
	<div class="login-form">
		<p>Name your team whatever you want</p>
		<div class="form-group">
			<form id="team-form" action='' method='POST'>
				{% csrf_token %}
				{{ form }}
				<button id="submit" class="btn button fregister" type='submit'>Create</button>
			</form>
		</div>

		<img id="loader-sign" class="hidden" src="{% static 'launcher-loader.gif' %}">
		<div id="loader-info" class="hidden">
			<h3>CREATING TEAMS AND SCHEDULE</h3>
			<p>It might take a while</p>
		</div>
	</div>
</div>
<script type="text/javascript" src="{% static '../../static/js/loading.js' %}"></script>
{% endblock %}

football_manager/app_football/templates/app_football/game.html
{% extends 'app_football/team.html' %}

{% block team %}
<div class="row">
    <div class="column-left-two">
        <div class="container">
            <h2 class="sub-header sub2">HOME TEAM</h2>
            <h3 class="sub-header sub2">{{ home.name }}</h3>

            <table class="table table2">
                <thead>
                <tr><th>Name</th><th>Position</th><th>Attack</th><th>Defence</th></tr>
                </thead>
                <tbody class="table-body">
                {% for player in home_players %}
                    <tr>
                        <td>{{ player.full_name }}</td>
                        <td>{{ player.get_position_display }}</td>
                        <td>{{ player.attack }}</td>
                        <td>{{ player.defence }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="column-right-two">
        <div class="container">
            <h2 class="sub-header sub2">AWAY TEAM</h2>
            <h3 class="sub-header sub2">{{ away.name }}</h3>

            <table class="table table2">
                <thead>
                <tr><th>Name</th><th>Position</th><th>Attack</th><th>Defence</th></tr>
                </thead>
                <tbody class="table-body">
                {% for player in away_players %}
                    <tr>
                        <td>{{ player.full_name }}</td>
                        <td>{{ player.get_position_display }}</td>
                        <td>{{ player.attack }}</td>
                        <td>{{ player.defence }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<form action="" method="POST">
        {% csrf_token %}
<input id="train" class="train-team btn button" style="margin-left: 1280px" type="submit" value="LET'S PLAY">
</form>
{% endblock %}

football_manager/app_football/templates/app_football/league_end.html
{% extends 'app_football/team.html' %}

{% block team %}

{% load static %}

<div class="container">
    <h2 class="sub-header">This season is finished</h2>
    <p>You can <strong>PLAY AGAIN</strong> with the same teams,</p>
    <p>you can start new season with <strong>NEW TEAMS</strong>,</p>
    <p>or you can start from the beginning with <strong>ALL NEW TEAMS</strong> (incuding yours)</p>

</div>

<form id="finish-form" action="" method="POST">
    {% csrf_token %}
    <div id="finish-btns" style="font-size: 1.5em; text-align: center; margin-top: 5em;">
        <input class="btn button" type="submit" name="play-again" value="PLAY AGAIN">
        <input id="new-teams" class="btn button" type="submit" name="new-teams" value="NEW TEAMS">
        <input style="padding-left: 25px; padding-right: 20px;" class="btn button" type="submit" name="all-new-teams" value="ALL NEW TEAMS">
    </div>
</form>

<img id="loader-sign" class="hidden" src="{% static 'launcher-loader.gif' %}">
<div id="loader-info" class="hidden">
    <h3>CREATING TEAMS AND SCHEDULE</h3>
    <p>It might take a while</p>
</div>

<script type="text/javascript" src="{% static '../../static/js/loader.js' %}"></script>

{% endblock %}

football_manager/app_football/templates/app_football/login.html
{% extends 'app_football/index.html' %}
		
		
{% block content %}
<div class="container login">

	<h2>Login form</h2>
    <div class="login-form">
        <div class="form-group">
            <form action='' method='POST'>
                {% csrf_token %}
                {{ form }}
                <button class="btn button flogin" type='submit'>Log In</button>
            </form>
        </div>
        <p id="register-info">If you don't have your profile, please <strong>REGISTER!</strong></p>
        <div class="register">
            <a href="{% url 'register' %}"><button class="btn button fregister">Register</button></a>
        </div>
    </div>


</div>

{% endblock %}

football_manager/app_football/templates/app_football/low_energy.html
{% extends 'app_football/team.html' %}

{% block team %}

{% load static %}


<div class="container" >
    <h1 class="sub-header">Not enough ENERGY</h1>
    <h2 class="sub-header">Try again later</h2>
</div>
<img style="width: 270px; margin-left: 43.6%; margin-top: 6px" src="{% static 'low-logo.png' %}">

{% endblock %}

football_manager/app_football/templates/app_football/personal_training.html
{% extends 'app_football/team.html' %}

{% block team %}
<div class="container">
    <h2 class="sub-header">PERSONAL TRAINING</h2>
    <p><strong>Personal training (energy cost 2)</strong> -  gives your player 2 points of attack or defence (max attack or defence value is 100</p>
        <h3>{{ player.full_name }}</h3>

        <p>Position: {{ player.get_position_display }}</p>

        <form action="" method="POST">
            {% csrf_token %}
            <table class="training-table">
                {% if player.attack >= 100 %}
                <tr><td>Attack: {{ player.attack }} </td><td><input class="btn train" type="submit" name="train_att" value='Train Attack' disabled></td></tr>
                {% else %}
                <tr><td>Attack: {{ player.attack }} </td><td><input class="btn train" type="submit" name="train_att" value='Train Attack'></td></tr>
                {% endif %}
                {% if player.defence >= 100 %}
                <tr><td>Defence: {{ player.defence }} </td><td><input class="btn train" type="submit" name="train_def" value='Train Defence' disabled></td></tr>
                {% else %}
                <tr><td>Defence: {{ player.defence }} </td><td><input class="btn train" type="submit" name="train_def" value='Train Defence'></td></tr>
                {% endif %}
            </table>
        </form>
</div>
{% endblock %}

football_manager/app_football/templates/app_football/player_edit.html
{% extends 'app_football/team.html' %}

{% block team %}
<div class="container">
    <h2>EDIT PLAYER</h2>
    <div class="login-form">
        <div class="form-group">
            <form action="" method="POST">
               {% csrf_token %}
               {{ form }}
               <input class="btn button flogin" type="submit" value="UPDATE">
           </form>
        </div>
    </div>
    <div id="player-info">
       <p>Position: {{ player.get_position_display }}</p>

       <p>Attack: {{ player.attack }}</p>

       <p>Defence: {{ player.defence }}</p>
    </div>
</div>
{% endblock %}

football_manager/app_football/templates/app_football/register_user_form.html
{% extends 'app_football/index.html' %}


{% block content %}
<div class="container login">

    <h2 >Registration Form</h2>
    <div class="login-form">
        <div class="form-group">
            <form action='' method='POST'>
                {% csrf_token %}
                {{ form }}
                <button class="btn button fregister" type='submit'>Register</button>
            </form>
        </div>
        <p id="register-info">If you're already registered, please <strong>LOG IN!</strong></p>
        <div class="register">
            <a href="{% url 'login' %}"><button class="btn button fregister">Log In</button></a>
        </div>
    </div>
</div>

{% endblock %}

football_manager/app_football/templates/app_football/table_view.html
{% extends 'app_football/team.html' %}

{% block team %}

    <div class="container">
        <h2 class="sub-header">LEAGUE TABLE</h2>
        <table class="table">
            <thead>
                <tr><th>Position</th><th>Team</th><th>Played</th><th>Wins</th><th>Draws</th><th>Loses</th><th>+/-</th><th>Points</th></tr>
            </thead>
            <tbody class="table-body">
                {% for team in teams %}
                    {% if team.user_id == user.id %}
                        <tr class="player-team">
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'team' %}">{{ team.name }}</a></td>
                            <td>{{ team.played }}</td>
                            <td>{{ team.wins }}</td>
                            <td>{{ team.draws }}</td>
                            <td>{{ team.loses }}</td>
                            <td>{{ team.goals_sum}}</td>
                            <td>{{ team.points }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ team.name }}</td>
                            <td>{{ team.played }}</td>
                            <td>{{ team.wins }}</td>
                            <td>{{ team.draws }}</td>
                            <td>{{ team.loses }}</td>
                            <td>{{ team.goals_sum}}</td>
                            <td>{{ team.points }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

football_manager/app_football/templates/app_football/team_training.html
{% extends 'app_football/team.html' %}

{% block team %}
<div class="container">
    <h2 class="sub-header">Team Training Center</h2>
    <p><strong>Team training (energy cost 4)</strong> - 3 random players gets randomly 2 points of attack or defence</p>
    <table class="table">
        <thead>
        <tr><th>Name</th><th>Position</th><th>Attack</th><th>Defence</th></tr>
        </thead>
        <tbody class="table-body">

        {% for player in players %}

            {% with player|stringformat:"s"|add:" attack" as attack %}
            {% with player|stringformat:"s"|add:" defence" as defence %}

            {% if attack in player_it %}
                <tr>
                    <td class="player-data">{{ player.full_name }}</td>
                    <td class="player-data">{{ player.get_position_display }}</td>
                    <td class="player-data added">{{ player.attack }}</td>
                    <td class="player-data">{{ player.defence }}</td>
                </tr>
            {% elif defence in player_it %}
                <tr>
                    <td class="player-data">{{ player.full_name }}</td>
                    <td class="player-data">{{ player.get_position_display }}</td>
                    <td class="player-data">{{ player.attack }}</td>
                    <td class="player-data added">{{ player.defence }}</td>
                </tr>
            {% else %}
                <tr>
                    <td class="player-data">{{ player.full_name }}</td>
                    <td class="player-data">{{ player.get_position_display }}</td>
                    <td class="player-data">{{ player.attack }}</td>
                    <td class="player-data">{{ player.defence }}</td>
                </tr>
            {% endif %}
            {% endwith %}
            {% endwith %}
        {% endfor %}
        </tbody>
    </table>
</div>
<form action="" method="POST">
    {% csrf_token %}
    <input id="train" class="btn button train-team" type="submit" name="team_train" value="TRAIN">
</form>
{% endblock %}

football_manager/app_football/templates/app_football/training_view.html
{% extends 'app_football/team.html' %}

{% block team %}
<div class="container training">
    <h2 class="sub-header">TRAINING CENTER</h2>
    <p><strong>Personal training (energy cost 2)</strong> -  gives your player 2 points of attack or defence</p>
    <p><strong>Team training (energy cost 4)</strong> - 3 random players gets randomly 2 points of attack or defence</p>

    <table class="table">
        <thead>
            <tr><th>Name</th><th>Position</th><th>Attack</th><th>Defence</th><th>Training</th></tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td class="player-data">{{ player.full_name }}</td>
                <td class="player-data">{{ player.get_position_display }}</td>
                <td class="player-data">{{ player.attack }}</td>
                <td class="player-data">{{ player.defence }}</td>
                <td><a href="{% url 'personal-training' player_pk=player.id %}"><button class="train-person button">TRAIN PERSONALLY</button></a></td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr><td></td><td></td><td></td><td></td><td><a href="{% url 'team-training' %}"><button class="team-train btn button">TEAM TRAINING</button></a></td></tr>
        </tfoot>
    </table>
</div>

{% endblock %}